name: islami
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_islamic_icons: any
  circle_nav_bar: any
  google_fonts: any
  shimmer: any
  flutter_native_splash: any
  icons_launcher: any
  provider: any
  shared_preferences: any
  flutter_gen: ^5.12.0
  dio:
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/
    - assets/quran/
    - assets/hadeth/ahadeth.txt

icons_launcher:
  image_path: "assets/logo2.jpg"
  platforms:
    android:
      enable: true
    ios:
      enable: true
    linux:
      enable: true
